In [4]:
import pandas as pd


df = pd.read_csv('./csv/clear_data.csv')
df

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s

In [5]:
china_india = df[df['Country'].isin(['China', 'India'])]
china_india

     Country ISO3  Year  Population  Population Growth  Growth Rate (%) Decade
2596   China  CHN  1960   667070000       1.251138e+07         1.280385  1960s
2597   China  CHN  1961   660330000      -6.740000e+06        -1.010389  1960s
2598   China  CHN  1962   665770000       5.440000e+06         0.823831  1960s
2599   China  CHN  1963   682335000       1.656500e+07         2.488096  1960s
2600   China  CHN  1964   698355000       1.602000e+07         2.347820  1960s
...      ...  ...   ...         ...                ...              ...    ...
6478   India  IND  2014  1295604184       1.475806e+07         1.152211  2010s
6479   India  IND  2015  1310152403       1.454822e+07         1.122891  2010s
6480   India  IND  2016  1324509589       1.435719e+07         1.095841  2010s
6481   India  IND  2017  1338658835       1.414925e+07         1.068263  2010s
6482   India  IND  2018  1352617328       1.395849e+07         1.042722  2010s

[118 rows x 7 columns]

In [7]:
pivot = china_india.pivot(index='Year', columns='Country', values='Growth Rate (%)')
pivot

Country     China     India
Year
1960     1.280385  1.914283
1961    -1.010389  2.018540
1962     0.823831  2.052689
1963     2.488096  2.078212
1964     2.347820  2.093148
1965     2.409949  2.101918
1966     2.826541  2.105327
1967     2.604025  2.113110
1968     2.645285  2.135518
1969     2.777885  2.176898
1970     2.800163  2.229020
1971     2.784991  2.283584
1972     2.487799  2.327872
1973     2.309664  2.354703
1974     2.087444  2.359309
1975     1.782085  2.348922
1976     1.559371  2.331427
1977     1.372108  2.317753
1978     1.347176  2.313125
1979     1.342864  2.321431
1980     1.262119  2.336398
1981     1.289192  2.350967
1982     1.483572  2.356006
1983     1.455440  2.347518
1984     1.320714  2.322362
1985     1.371012  2.285581
1986     1.498516  2.245810
1987     1.616532  2.207906
1988     1.623103  2.169967
1989     1.544983  2.133303
1990     1.478121  2.097789
1991     1.373785  2.060674
1992     1.233077  2.023376
1993     1.156253  1.990180
1994     1.136672  1.962249
1995     1.092433  1.937471
1996     1.053654  1.913292
1997     1.028705  1.886751
1998     0.964169  1.856684
1999     0.869611  1.821959
2000     0.791069  1.783849
2001     0.729025  1.743797
2002     0.672249  1.703917
2003     0.624805  1.665203
2004     0.595700  1.628424
2005     0.589858  1.592254
2006     0.559936  1.557704
2007     0.523638  1.520668
2008     0.513702  1.475672
2009     0.498620  1.420578
2010     0.484128  1.359497
2011     0.480300  1.296913
2012     0.488420  1.239239
2013     0.494930  1.190041
2014     0.507596  1.152211
2015     0.509430  1.122891
2016     0.542947  1.095841
2017     0.560687  1.068263
2018     0.456940  1.042722

In [10]:
pivot['diff'] = (pivot['China'] - pivot['India']).abs()
pivot

Country     China     India      diff
Year
1960     1.280385  1.914283  0.633898
1961    -1.010389  2.018540  3.028929
1962     0.823831  2.052689  1.228859
1963     2.488096  2.078212  0.409885
1964     2.347820  2.093148  0.254673
1965     2.409949  2.101918  0.308031
1966     2.826541  2.105327  0.721215
1967     2.604025  2.113110  0.490915
1968     2.645285  2.135518  0.509767
1969     2.777885  2.176898  0.600988
1970     2.800163  2.229020  0.571144
1971     2.784991  2.283584  0.501407
1972     2.487799  2.327872  0.159927
1973     2.309664  2.354703  0.045038
1974     2.087444  2.359309  0.271866
1975     1.782085  2.348922  0.566837
1976     1.559371  2.331427  0.772056
1977     1.372108  2.317753  0.945645
1978     1.347176  2.313125  0.965949
1979     1.342864  2.321431  0.978567
1980     1.262119  2.336398  1.074279
1981     1.289192  2.350967  1.061775
1982     1.483572  2.356006  0.872434
1983     1.455440  2.347518  0.892078
1984     1.320714  2.322362  1.001648
1985     1.371012  2.285581  0.914568
1986     1.498516  2.245810  0.747294
1987     1.616532  2.207906  0.591374
1988     1.623103  2.169967  0.546864
1989     1.544983  2.133303  0.588319
1990     1.478121  2.097789  0.619668
1991     1.373785  2.060674  0.686889
1992     1.233077  2.023376  0.790299
1993     1.156253  1.990180  0.833927
1994     1.136672  1.962249  0.825577
1995     1.092433  1.937471  0.845037
1996     1.053654  1.913292  0.859638
1997     1.028705  1.886751  0.858046
1998     0.964169  1.856684  0.892515
1999     0.869611  1.821959  0.952348
2000     0.791069  1.783849  0.992780
2001     0.729025  1.743797  1.014772
2002     0.672249  1.703917  1.031667
2003     0.624805  1.665203  1.040399
2004     0.595700  1.628424  1.032724
2005     0.589858  1.592254  1.002396
2006     0.559936  1.557704  0.997768
2007     0.523638  1.520668  0.997030
2008     0.513702  1.475672  0.961970
2009     0.498620  1.420578  0.921958
2010     0.484128  1.359497  0.875369
2011     0.480300  1.296913  0.816613
2012     0.488420  1.239239  0.750819
2013     0.494930  1.190041  0.695111
2014     0.507596  1.152211  0.644616
2015     0.509430  1.122891  0.613461
2016     0.542947  1.095841  0.552894
2017     0.560687  1.068263  0.507576
2018     0.456940  1.042722  0.585782

In [11]:
max_diff_year = pivot[pivot['diff'] == pivot['diff'].max()]

print(max_diff_year)

Country     China    India      diff
Year
1961    -1.010389  2.01854  3.028929