In [62]:
import pandas as pd

In [63]:
df = pd.read_csv("./csv/clear_data.csv")
df

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s

In [64]:
max_year = df['Year'].idxmax()
max_year = df.loc[max_year, "Year"]
print(max_year)
# print(max_country)

min_year = max_year - 10


print(min_year)

2018
2008

In [65]:
last_10_year = df[df["Year"].between(min_year, max_year)]
last_10_year

last_10_year = last_10_year.sort_values("Year")
last_10_year

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
14307,Turkmenistan,TKM,2008,4935767,65626.0,1.347517,2000s
12280,Sierra Leone,SLE,2008,6133603,143970.0,2.403653,2000s
11130,Papua New Guinea,PNG,2008,6976201,167687.0,2.462902,2000s
5882,High income,HIC,2008,1141674064,9519297.0,0.840812,2000s
5823,Heavily indebted poor countries (HIPC),HPC,2008,590590368,16030108.0,2.789979,2000s
...,...,...,...,...,...,...,...
11081,Panama,PAN,2018,4176873,70102.0,1.706986,2010s
15290,"Yemen, Rep.",YEM,2018,28498687,663866.0,2.385020,2010s
11140,Papua New Guinea,PNG,2018,8606316,168287.0,1.994388,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.0,1.420781,2010s
176,Algeria,DZA,2018,42228429,839231.0,2.027657,2010s

In [66]:
change = (last_10_year.groupby("Country").agg(start = ("Population", "first"), end = ("Population", "last")))
change

                         start         end
Country
Afghanistan           27722276    37172386
Albania                2947314     2866376
Algeria               34730608    42228429
American Samoa           57492       55465
Andorra                  83862       77006
...                        ...         ...
West Bank and Gaza     3591977     4569087
World               6757887172  7594270356
Yemen, Rep.           21892146    28498687
Zambia                12848530    17351822
Zimbabwe              12379549    14439018

[263 rows x 2 columns]

In [67]:
change['Growth %'] = (change['end'] - change['start']) / change['start'] * 100
change

                         start         end   Growth %
Country
Afghanistan           27722276    37172386  34.088507
Albania                2947314     2866376  -2.746161
Algeria               34730608    42228429  21.588511
American Samoa           57492       55465  -3.525708
Andorra                  83862       77006  -8.175336
...                        ...         ...        ...
West Bank and Gaza     3591977     4569087  27.202568
World               6757887172  7594270356  12.376401
Yemen, Rep.           21892146    28498687  30.177677
Zambia                12848530    17351822  35.049083
Zimbabwe              12379549    14439018  16.636058

[263 rows x 3 columns]

In [68]:
top3 = change.sort_values("Growth %", ascending=False).head(3)

top3

           start      end   Growth %
Country
Qatar    1436665  2781677  93.620433
Oman     2750963  4829483  75.556087
Kuwait   2656009  4137309  55.771648

# 2

In [69]:
df = pd.read_csv('./csv/clear_data.csv')
df

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s

In [70]:
max_year = df["Year"].idxmax()
max_year= df.loc[max_year, "Year"]

min_year = max_year - 10

print(max_year)
print(min_year)

2018
2008

In [71]:
last_10_year = df[df['Year'].between(min_year, max_year)]
last_10_year

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
48,Afghanistan,AFG,2008,27722276,621740.0,2.294198,2000s
49,Afghanistan,AFG,2009,28394813,672537.0,2.425980,2000s
50,Afghanistan,AFG,2010,29185507,790694.0,2.784642,2010s
51,Afghanistan,AFG,2011,30117413,931906.0,3.193044,2010s
52,Afghanistan,AFG,2012,31161376,1043963.0,3.466310,2010s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.0,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.0,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.0,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.0,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.0,1.420781,2010s

In [72]:
change = last_10_year.groupby('Country').agg(start = ("Population", "first"), end = ("Population", "last"))
change

                         start         end
Country
Afghanistan           27722276    37172386
Albania                2947314     2866376
Algeria               34730608    42228429
American Samoa           57492       55465
Andorra                  83862       77006
...                        ...         ...
West Bank and Gaza     3591977     4569087
World               6757887172  7594270356
Yemen, Rep.           21892146    28498687
Zambia                12848530    17351822
Zimbabwe              12379549    14439018

[263 rows x 2 columns]

In [73]:
change['diff'] = change['end'] - change['start']
change

                         start         end       diff
Country
Afghanistan           27722276    37172386    9450110
Albania                2947314     2866376     -80938
Algeria               34730608    42228429    7497821
American Samoa           57492       55465      -2027
Andorra                  83862       77006      -6856
...                        ...         ...        ...
West Bank and Gaza     3591977     4569087     977110
World               6757887172  7594270356  836383184
Yemen, Rep.           21892146    28498687    6606541
Zambia                12848530    17351822    4503292
Zimbabwe              12379549    14439018    2059469

[263 rows x 3 columns]

In [76]:
top_3 = change.sort_values("diff").head(3)

top_3

                                    start        end     diff
Country
Syrian Arab Republic             20664038   16906283 -3757755
Central Europe and the Baltics  105001883  102511922 -2489961
Ukraine                          46258200   44622516 -1635684