In [72]:
import pandas as pd

In [ ]:
df = pd.read_csv("./csv/clear_data.csv")
df

       Population  Year
0         8996973  1960
1         9169410  1961
2         9351441  1962
3         9543205  1963
4         9744781  1964
...           ...   ...
15404    13586681  2014
15405    13814629  2015
15406    14030390  2016
15407    14236745  2017
15408    14439018  2018

[15409 rows x 2 columns]

In [74]:
df = df.sort_values(["Country", "Year"])
df

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s

In [75]:
df_future = df[["Country", "Year", "Population"]].copy()
df_future

           Country  Year  Population
0      Afghanistan  1960     8996973
1      Afghanistan  1961     9169410
2      Afghanistan  1962     9351441
3      Afghanistan  1963     9543205
4      Afghanistan  1964     9744781
...            ...   ...         ...
15404     Zimbabwe  2014    13586681
15405     Zimbabwe  2015    13814629
15406     Zimbabwe  2016    14030390
15407     Zimbabwe  2017    14236745
15408     Zimbabwe  2018    14439018

[15409 rows x 3 columns]

In [76]:
df_future["Year"] = df_future["Year"] - 3
df_future

           Country  Year  Population
0      Afghanistan  1957     8996973
1      Afghanistan  1958     9169410
2      Afghanistan  1959     9351441
3      Afghanistan  1960     9543205
4      Afghanistan  1961     9744781
...            ...   ...         ...
15404     Zimbabwe  2011    13586681
15405     Zimbabwe  2012    13814629
15406     Zimbabwe  2013    14030390
15407     Zimbabwe  2014    14236745
15408     Zimbabwe  2015    14439018

[15409 rows x 3 columns]

In [77]:
df_future = df_future.rename(columns={"Population":"Population_3y"})
df_future

           Country  Year  Population_3y
0      Afghanistan  1957        8996973
1      Afghanistan  1958        9169410
2      Afghanistan  1959        9351441
3      Afghanistan  1960        9543205
4      Afghanistan  1961        9744781
...            ...   ...            ...
15404     Zimbabwe  2011       13586681
15405     Zimbabwe  2012       13814629
15406     Zimbabwe  2013       14030390
15407     Zimbabwe  2014       14236745
15408     Zimbabwe  2015       14439018

[15409 rows x 3 columns]

In [78]:
df_merged = df.merge(df_future, on = ["Country", "Year"], how = "left")
# df_merged.to_csv("./csv/temp.csv")
df_merged

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade,Population_3y
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s,9543205.0
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s,9744781.0
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s,9956320.0
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s,10174836.0
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s,10399926.0
...,...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s,14236745.0
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s,14439018.0
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s,NaN
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s,NaN
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s,NaN

In [79]:
df

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s

In [80]:
df_merged= df_merged.dropna(subset=["Population_3y"])
df_merged

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade,Population_3y
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s,9543205.0
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s,9744781.0
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s,9956320.0
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s,10174836.0
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s,10399926.0
...,...,...,...,...,...,...,...,...
15401,Zimbabwe,ZWE,2011,12894316,196593.000000,1.548254,2010s,13586681.0
15402,Zimbabwe,ZWE,2012,13115131,220815.000000,1.712499,2010s,13814629.0
15403,Zimbabwe,ZWE,2013,13350356,235225.000000,1.793539,2010s,14030390.0
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s,14236745.0
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s,14439018.0

In [81]:
df_merged["Growth_3y"] = df_merged["Population_3y"] - df_merged["Population"]
df_merged

C:\Users\yokko\AppData\Local\Temp\ipykernel_8172\2666742285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged["Growth_3y"] = df_merged["Population_3y"] - df_merged["Population"]

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade,Population_3y,Growth_3y
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s,9543205.0,546232.0
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s,9744781.0,575371.0
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s,9956320.0,604879.0
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s,10174836.0,631631.0
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s,10399926.0,655145.0
...,...,...,...,...,...,...,...,...,...
15401,Zimbabwe,ZWE,2011,12894316,196593.000000,1.548254,2010s,13586681.0,692365.0
15402,Zimbabwe,ZWE,2012,13115131,220815.000000,1.712499,2010s,13814629.0,699498.0
15403,Zimbabwe,ZWE,2013,13350356,235225.000000,1.793539,2010s,14030390.0,680034.0
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s,14236745.0,650064.0
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s,14439018.0,624389.0

In [82]:
idx_max = df_merged["Growth_3y"].idxmax()
idx_max

np.int64(15200)

In [83]:
best_row = df_merged.loc[idx_max]
best_row

Country                     World
ISO3                          WLD
Year                         1987
Population             5013576387
Population Growth      87775053.0
Growth Rate (%)          1.781945
Decade                      1980s
Population_3y        5281340078.0
Growth_3y             267763691.0
Name: 15200, dtype: object

In [84]:
best_country = best_row["Country"]
best_start_year = int(best_row["Year"])
best_end_year = best_start_year + 3
best_growth = best_row["Growth_3y"]

print(f"Страна: {best_country} ({best_start_year} - {best_end_year}) c приростом населения в {best_growth}")

Страна: World (1987 - 1990) c приростом населения в 267763691.0

In [85]:
df

,Country,ISO3,Year,Population,Population Growth,Growth Rate (%),Decade
0,Afghanistan,AFG,1960,8996973,485782.982759,2.505003,1960s
1,Afghanistan,AFG,1961,9169410,172437.000000,1.916611,1960s
2,Afghanistan,AFG,1962,9351441,182031.000000,1.985199,1960s
3,Afghanistan,AFG,1963,9543205,191764.000000,2.050636,1960s
4,Afghanistan,AFG,1964,9744781,201576.000000,2.112246,1960s
...,...,...,...,...,...,...,...
15404,Zimbabwe,ZWE,2014,13586681,236325.000000,1.770178,2010s
15405,Zimbabwe,ZWE,2015,13814629,227948.000000,1.677731,2010s
15406,Zimbabwe,ZWE,2016,14030390,215761.000000,1.561830,2010s
15407,Zimbabwe,ZWE,2017,14236745,206355.000000,1.470772,2010s
15408,Zimbabwe,ZWE,2018,14439018,202273.000000,1.420781,2010s

In [86]:
# для удаления
df = df[~df["Country"].isin(["World", "Middle income"])]

In [87]:
df.to_csv("./csv/temp.csv")